[package]
name = "vault"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "2.0.13"
solana-nostd-sha256 = "0.1.3"

[dev-dependencies]
mollusk-svm = "0.0.6"
solana-sdk = "2.0.13"